spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AC2?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    path: /api-docs